@startuml

title __CRYPTDATA's Class Diagram__\n

  namespace com.gmail.ib.projectCrypt {
    namespace backend.cryptData {
      class com.gmail.ib.projectCrypt.backend.cryptData.API {
          {static} - apiKey : String
          {static} + main()
          {static} - jsonDataParser()
          {static} - makeAPICall()
          {static} - updateDB()
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace backend.cryptData {
      class com.gmail.ib.projectCrypt.backend.cryptData.SQLConnector {
          + SQLConnection()
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace backend.cryptData {
      class com.gmail.ib.projectCrypt.backend.cryptData.cryptCurrencyPriceData {
          - dateAdded : String
          - market_cap : double
          - name : String
          - percentChange_24h : double
          - percent_change_1h : double
          - percent_change_7d : double
          - price : double
          - slug : String
          - symbol : String
          - volume_24h : double
          + cryptCurrencyPriceData()
          + cryptCurrencyPriceData()
          + cryptCurrencyPriceData()
          + cryptCurrencyPriceData()
          + getDateAdded()
          + getMarket_cap()
          + getName()
          + getPercentChange_24h()
          + getPercent_change_1h()
          + getPercent_change_7d()
          + getPrice()
          + getSlug()
          + getSymbol()
          + getVolume_24h()
          + setDateAdded()
          + setMarket_cap()
          + setName()
          + setPercentChange_24h()
          + setPercent_change_1h()
          + setPercent_change_7d()
          + setPrice()
          + setSlug()
          + setSymbol()
          + setVolume_24h()
      }
    }
  }
  

  com.gmail.ib.projectCrypt.backend.cryptData.cryptCurrencyPriceData .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
