@startuml

title __DASHBOARD's Class Diagram__\n

  namespace com.gmail.ib.projectCrypt {
    namespace ui {
      namespace dashboard {
        class com.gmail.ib.projectCrypt.ui.dashboard.Dashboard {
            + Dashboard()
        }
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace ui {
      namespace dashboard {
        class com.gmail.ib.projectCrypt.ui.dashboard.card {
            + card()
        }
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace ui {
      namespace dashboard {
        class com.gmail.ib.projectCrypt.ui.dashboard.chart {
            + chart()
        }
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace ui {
      namespace dashboard {
        class com.gmail.ib.projectCrypt.ui.dashboard.content {
            + content()
        }
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace ui {
      namespace dashboard {
        class com.gmail.ib.projectCrypt.ui.dashboard.dashboardContent {
            + dashboardContent()
        }
      }
    }
  }
  

  namespace com.gmail.ib.projectCrypt {
    namespace ui {
      namespace dashboard {
        class com.gmail.ib.projectCrypt.ui.dashboard.trendingCurrencies {
            + trendingCurrencies()
        }
      }
    }
  }
  

  com.gmail.ib.projectCrypt.ui.dashboard.Dashboard -up-|> com.vaadin.flow.component.orderedlayout.VerticalLayout
  com.gmail.ib.projectCrypt.ui.dashboard.card -up-|> com.vaadin.flow.component.orderedlayout.VerticalLayout
  com.gmail.ib.projectCrypt.ui.dashboard.chart -up-|> com.vaadin.flow.component.orderedlayout.VerticalLayout
  com.gmail.ib.projectCrypt.ui.dashboard.content -up-|> com.vaadin.flow.component.orderedlayout.VerticalLayout
  com.gmail.ib.projectCrypt.ui.dashboard.dashboardContent -up-|> com.vaadin.flow.component.orderedlayout.VerticalLayout
  com.gmail.ib.projectCrypt.ui.dashboard.trendingCurrencies .up.|> com.vaadin.flow.component.HasSize
  com.gmail.ib.projectCrypt.ui.dashboard.trendingCurrencies -up-|> com.vaadin.flow.component.orderedlayout.HorizontalLayout


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
